# Site Settings
title: Suleman S. Manji | Business Process Automation Expert
description: Business Process Automation Specialist with expertise in Microsoft 365, cloud services, and AI-driven process improvements.
url: "https://www.sulemanji.com"
baseurl: ""

# Jekyll and GitHub Pages Configuration
markdown: kramdown
highlighter: rouge

# Theme Configuration
theme: jekyll-text-theme
remote_theme: "kitian616/jekyll-TeXt-theme"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Theme-Specific Settings
text_skin: default
highlight_theme: default
lang: en
timezone: America/Chicago

# Author Information
author:
  name: Suleman S. Manji
  email: ssmanji89@gmail.com
  links:
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/sulemanmanji
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/ssmanji89

# Build Settings
incremental: false
future: false

# Exclude from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Performance and CDN
image_cdn: https://cdn.sulemanji.com

# GitHub Pages Settings
github:
  is_project_page: true
